# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(499, 523)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(8, 10, 481, 221))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btn_package_start = QtWidgets.QPushButton(self.tab_2)
        self.btn_package_start.setGeometry(QtCore.QRect(162, 150, 113, 32))
        self.btn_package_start.setObjectName("btn_package_start")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 471, 61))
        self.groupBox.setObjectName("groupBox")
        self.pb_select_package_path = QtWidgets.QPushButton(self.groupBox)
        self.pb_select_package_path.setGeometry(QtCore.QRect(390, 20, 81, 41))
        self.pb_select_package_path.setObjectName("pb_select_package_path")
        self.le_package_path = QtWidgets.QLineEdit(self.groupBox)
        self.le_package_path.setEnabled(False)
        self.le_package_path.setGeometry(QtCore.QRect(8, 23, 381, 31))
        self.le_package_path.setAutoFillBackground(False)
        self.le_package_path.setText("")
        self.le_package_path.setDragEnabled(False)
        self.le_package_path.setObjectName("le_package_path")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 89, 81, 31))
        self.label.setObjectName("label")
        self.cb_proces_type = QtWidgets.QComboBox(self.tab_2)
        self.cb_proces_type.setGeometry(QtCore.QRect(110, 90, 351, 31))
        self.cb_proces_type.setObjectName("cb_proces_type")
        self.cb_proces_type.addItem("")
        self.cb_proces_type.addItem("")
        self.cb_proces_type.addItem("")
        self.cb_proces_type.addItem("")
        self.cb_proces_type.addItem("")
        self.cb_proces_type.addItem("")
        self.cb_proces_type.addItem("")
        self.cb_proces_type.addItem("")
        self.cb_proces_type.addItem("")
        self.cb_proces_type.addItem("")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(10, 94, 91, 20))
        self.label_5.setObjectName("label_5")
        self.btn_protocol_build_start = QtWidgets.QPushButton(self.tab_3)
        self.btn_protocol_build_start.setGeometry(QtCore.QRect(162, 150, 113, 32))
        self.btn_protocol_build_start.setObjectName("btn_protocol_build_start")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 471, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pb_select_xml_path = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_select_xml_path.setGeometry(QtCore.QRect(390, 20, 81, 41))
        self.pb_select_xml_path.setObjectName("pb_select_xml_path")
        self.le_line_xml_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_line_xml_path.setEnabled(False)
        self.le_line_xml_path.setGeometry(QtCore.QRect(8, 23, 381, 31))
        self.le_line_xml_path.setAutoFillBackground(False)
        self.le_line_xml_path.setText("")
        self.le_line_xml_path.setDragEnabled(False)
        self.le_line_xml_path.setObjectName("le_line_xml_path")
        self.cb_protocol_type = QtWidgets.QComboBox(self.tab_3)
        self.cb_protocol_type.setGeometry(QtCore.QRect(110, 85, 351, 41))
        self.cb_protocol_type.setObjectName("cb_protocol_type")
        self.cb_protocol_type.addItem("")
        self.cb_protocol_type.addItem("")
        self.cb_protocol_type.addItem("")
        self.cb_protocol_type.addItem("")
        self.cb_protocol_type.addItem("")
        self.cb_protocol_type.addItem("")
        self.cb_protocol_type.addItem("")
        self.cb_protocol_type.addItem("")
        self.cb_protocol_type.addItem("")
        self.cb_protocol_type.addItem("")
        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(3, 240, 490, 281))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pte_log = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.pte_log.setGeometry(QtCore.QRect(10, 29, 471, 241))
        self.pte_log.setPlainText("")
        self.pte_log.setPlaceholderText("")
        self.pte_log.setObjectName("pte_log")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #信号槽
        #多媒体文件夹助手信号
        self.pb_select_package_path.clicked.connect(self.selectPackagePath)
        self.cb_proces_type.currentIndexChanged.connect(self.changePackageProcesType)
        self.btn_package_start.clicked.connect(self.packageProcesStart)
        #线路xml协议生成信号
        self.pb_select_xml_path.clicked.connect(self.selectLineXmlPath)
        self.cb_protocol_type.currentIndexChanged.connect(self.changeLineXmlProtocolType)
        self.btn_protocol_build_start.clicked.connect(self.xmlProtocolProcesStart)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "中航讯多媒体小工具"))
        self.btn_package_start.setText(_translate("MainWindow", "开始"))
        self.groupBox.setTitle(_translate("MainWindow", "请选择cictecMidea文件夹的路径"))
        self.pb_select_package_path.setText(_translate("MainWindow", "浏览"))
        self.label.setText(_translate("MainWindow", "请选择功能："))
        self.cb_proces_type.setItemText(0, _translate("MainWindow", "媒体资源下载"))
        self.cb_proces_type.setItemText(1, _translate("MainWindow", "APK拷贝"))
        self.cb_proces_type.setItemText(2, _translate("MainWindow", "离线包校验"))
        self.cb_proces_type.setItemText(3, _translate("MainWindow", "预留功能"))
        self.cb_proces_type.setItemText(4, _translate("MainWindow", "预留功能"))
        self.cb_proces_type.setItemText(5, _translate("MainWindow", "预留功能"))
        self.cb_proces_type.setItemText(6, _translate("MainWindow", "预留功能"))
        self.cb_proces_type.setItemText(7, _translate("MainWindow", "预留功能"))
        self.cb_proces_type.setItemText(8, _translate("MainWindow", "预留功能"))
        self.cb_proces_type.setItemText(9, _translate("MainWindow", "预留功能"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "媒体文件夹助手"))
        self.label_5.setText(_translate("MainWindow", "请选择协议："))
        self.btn_protocol_build_start.setText(_translate("MainWindow", "开始"))
        self.groupBox_2.setTitle(_translate("MainWindow", "请选择线路xml文件"))
        self.pb_select_xml_path.setText(_translate("MainWindow", "浏览"))
        self.cb_protocol_type.setItemText(0, _translate("MainWindow", "网智协议"))
        self.cb_protocol_type.setItemText(1, _translate("MainWindow", "西安协议"))
        self.cb_protocol_type.setItemText(2, _translate("MainWindow", "预留协议"))
        self.cb_protocol_type.setItemText(3, _translate("MainWindow", "预留协议"))
        self.cb_protocol_type.setItemText(4, _translate("MainWindow", "预留协议"))
        self.cb_protocol_type.setItemText(5, _translate("MainWindow", "预留协议"))
        self.cb_protocol_type.setItemText(6, _translate("MainWindow", "预留协议"))
        self.cb_protocol_type.setItemText(7, _translate("MainWindow", "预留协议"))
        self.cb_protocol_type.setItemText(8, _translate("MainWindow", "预留协议"))
        self.cb_protocol_type.setItemText(9, _translate("MainWindow", "预留协议"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "485协议模拟助手"))
        self.groupBox_4.setTitle(_translate("MainWindow", "日志"))

